# https://taskfile.dev

version: "3"

vars:
  TESTIMAGE_TAG: dcr.zekro.de/leuchtturm-testimage
  TESTIMAGE_CONTAINER_NAME: leuchtturm-testimage

tasks:
  run:
    desc: Run the leuchtturm executable
    env:
      LT_LOGLEVEL: debug
    cmds:
      - go run -v cmd/leuchtturm/main.go {{.CLI_ARGS}}

  test:
    desc: Run unti tests
    cmds:
      - go test -v -cover ./...

  testimage:build:
    desc: Build the testing Docker image
    vars:
      VERSION: '{{or .CLI_ARGS "latest"}}'
    cmds:
      - docker build testimage
        --build-arg BUILD_VERSION={{.VERSION}}
        --tag {{.TESTIMAGE_TAG}}:{{.VERSION}}
        --no-cache

  testimage:docker-compose:
    desc: Run docker compose on the test image stack
    aliases:
      - dc
    cmds:
      - docker compose -f testimage/docker-compose.yml {{.CLI_ARGS}}

  testimage:up:
    desc: Stop the testing Docker image
    aliases:
      - up
    cmds:
      - task: testimage:docker-compose
        vars:
          CLI_ARGS: up -d {{.CLI_ARGS}}
